name: CI with GitHub Actions using Maven and JUnit | © 2022 by giao.lang

on:
  push:
    branches: [ main ]  # Lấy code từ nhánh main nếu có ai push code lên
  pull_request:
    branches: [ main ]  # Lấy code từ nhánh main nếu có ai gửi pull request  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Kiểm tra và lấy mã nguồn từ kho GitHub
      - name: Check-out repository
        uses: actions/checkout@v3

      # Cài đặt JDK 18 để build dự án
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'  # Sử dụng phiên bản JDK 18
          distribution: 'temurin'
          cache: maven

      # Build dự án bằng Maven
      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      # Tạo thư mục staging và sao chép file .jar cần thiết vào đó
      - name: Distribute jar-war file
        run: |
          mkdir -p staging
          cp target/*.jar staging  # Sao chép tất cả file .jar vào staging

      # Tạo một artifact để download (ví dụ: file .jar)
      - name: Make hyperlink to jar-war file
        uses: actions/upload-artifact@v3
        with:
          name: 1.0-SNAPSHOT.jar  # Tên artifact bạn muốn upload
          path: staging  # Thư mục staging chứa file .jar
